[package]
name = "sentinel-api"
version = { workspace = true }
edition = "2021"
license = { workspace = true }
publish = false

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tonic-reflection = { workspace = true }
tonic-health = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
async-trait = "0.1"
arc-swap = { workspace = true }
sysinfo = { workspace = true }
async-stream = "0.3"
tokio-stream = "0.1"

sentinel-core = { path = "../sentinel-core" }
sentinel-events = { path = "../sentinel-events" }
sentinel-storage = { path = "../sentinel-storage" }
sentinel-config = { path = "../sentinel-config" }
sentinel-event-bus = { path = "../sentinel-event-bus" }
sentinel-ai = { path = "../sentinel-ai" }
sentinel-rule-engine = { path = "../sentinel-rule-engine" }
