[package]
name = "sentinel-sigma"
version = { workspace = true }
edition = "2021"
license = { workspace = true }
publish = false

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_yaml = "0.9"
serde_json = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
regex = "1"
uuid = { workspace = true }
